export const UTD_MAJORS = [
  "Accounting",
  "Accounting and Analytics",
  "Actuarial Science",
  "American Studies", 
  "Animation",
  "Animation and Games", 
  "Applied Cognition and Neuroscience",
  "Applied Sociology",
  "Art History",
  "Artificial Intelligence for Biomedical Sciences",
  "Arts, Technology, and Emerging Communication",
  "Audiology",
  "Biochemistry",
  "Bioinformatics and Computational Biology",
  "Biology", 
  "Biomedical Engineering", 
  "Biomedical Sciences", 
  "Biotechnology",
  "Business Administration", 
  "Business Analytics and Artificial Intelligence", 
  "Chemistry", 
  "Child Learning and Development", 
  "Cognition and Neuroscience",
  "Cognitive Science",
  "Computational and Geospations Science",
  "Computer Engineering",
  "Computer Information Systems and Technology",
  "Computer Science",
  "Criminology",
  "Cyber Security, Technology, and Policy",
  "Cybersecurity and Risk Management",
  "Cybersecurity Technology and Policy", 
  "Data Science",
  "Data Science and Statistics",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Energy Management",
  "Engineering",
  "Finance",
  "Financial Technology and Analytics",
  "Game Development",
  "Geosciences",
  "Geospatial Information Sciences",
  "Global Business",
  "Healthcare Administration and Leadership",
  "Healthcare Leadership and Management",
  "Healthcare Management",
  "Healthcare Studies",
  "History",
  "Human Development and Early Childhood Disorders",
  "Human Resource Management",
  "Humanities",
  "Information Technology and Management", 
  "Innovation and Entrepreneurship",
  "Interdisciplinary Studies",
  "International Management Studies", 
  "International Political Economy", 
  "Latin American Studies", 
  "Leadership and Organizational Development", 
  "Literature", 
  "Management Science", 
  "Marketing", 
  "Materials Science and Engineering", 
  "Mathematics", 
  "Mathematics Education", 
  "Mechanical Engineering", 
  "Media Arts and Design", 
  "Molecular and Cell Biology", 
  "Molecular Biology", 
  "Neuroscience", 
  "Philosophy", 
  "Physics", 
  "Political Science", 
  "Professional Communication and Digital Media Studies", 
  "Psychology", 
  "Public Affairs", 
  "Public Health", 
  "Public Policy", 
  "Public Policy and Political Economy",
  "Science Education", 
  "Social Data Analytics and Research", 
  "Sociology",
  "Software Engineering", 
  "Speech, Language, and Hearing Sciences",
  "Speech-Language Pathology",
  "Supply Chain Management", 
  "Supply Chain Management and Analytics", 
  "Sustainability Planning and Policy",
  "Systems Engineering",
  "Systems Engineering and Management",
  "Visual and Perfoming Arts"
].sort(); // Alphabetizes 

export const UTD_DEGREES = [
  "Bachelor of Science (BS)",
  "Bachelor of Arts (BA)",
  "Master of Science (MS)",
  "Master of Business Administration (MBA)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Philosophy (PhD)"  
];

export const ACADEMIC_YEARS = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Graduate",
];