ALTER TYPE "EventTag" ADD VALUE 'ACADEMY';
ALTER TYPE "EventTag" ADD VALUE 'INNOVATION';
ALTER TYPE "EventTag" ADD VALUE 'MENTOR';
ALTER TYPE "EventTag" ADD VALUE 'MENTEE';
ALTER TYPE "EventTag" ADD VALUE 'OFFICER';
